services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tyuiu_recommendations
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8433:5432"

  tyuiu_recommendations:
    build: .
    restart: unless-stopped
    volumes:
      - .:/tyuiu_recommendations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tyuiu_recommendations
    ports:
      - "8002:8000"
    depends_on:
      - postgres


volumes:
  postgres_data: