version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-data: {}
