"""Add relations

Revision ID: 3ba52869b89f
Revises: 2ef26c67fae4
Create Date: 2025-05-25 16:06:00.582813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba52869b89f'
down_revision: Union[str, None] = '2ef26c67fae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entrance_exams', 'directions', ['direction_id'], ['direction_id'])
    op.create_foreign_key(None, 'passing_points', 'directions', ['direction_id'], ['direction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passing_points', type_='foreignkey')
    op.drop_constraint(None, 'entrance_exams', type_='foreignkey')
    # ### end Alembic commands ###
