"""Initial revision

Revision ID: bc738a2cc8d9
Revises: 
Create Date: 2025-05-05 19:05:19.687940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc738a2cc8d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('education_form', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_id')
    )
    op.create_index('direction_index', 'directions', ['direction_id'], unique=False)
    op.create_table('entrance_exams',
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.direction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passing_points',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.direction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passing_points')
    op.drop_table('entrance_exams')
    op.drop_index('direction_index', table_name='directions')
    op.drop_table('directions')
    # ### end Alembic commands ###
