"""New tables structure

Revision ID: 2ef26c67fae4
Revises: bc738a2cc8d9
Create Date: 2025-05-24 19:40:08.448346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef26c67fae4'
down_revision: Union[str, None] = 'bc738a2cc8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directions', 'direction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('direction_index', table_name='directions')
    op.create_index('direction_index', 'directions', ['id'], unique=False)
    op.drop_constraint('entrance_exams_direction_id_fkey', 'entrance_exams', type_='foreignkey')
    op.drop_constraint('passing_points_direction_id_fkey', 'passing_points', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('passing_points_direction_id_fkey', 'passing_points', 'directions', ['direction_id'], ['direction_id'])
    op.create_foreign_key('entrance_exams_direction_id_fkey', 'entrance_exams', 'directions', ['direction_id'], ['direction_id'])
    op.drop_index('direction_index', table_name='directions')
    op.create_index('direction_index', 'directions', ['direction_id'], unique=False)
    op.alter_column('directions', 'direction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
